base:
  api_base_url: 'https://api1-pp.klokapp.ai/v1' # 不用改
  referral_code: "VECHW2KC"  # 填写你的邀请码

runner:
  thread_count: 1  # 线程池大小，同时跑多少个号
  max_thread_delay: 60  # 最大线程延迟，单位秒

# 定时任务配置
scheduler:
  jobs:
    - name: "chat_daily"
      schedule: "0 9 * * *"  # 每天上午8点
